In [1]:
#import all libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
aqi=pd.read_csv("aqi.csv")

In [3]:
aqi1=aqi.dropna(axis=1)
aqi1

,date,state,area,number_of_monitoring_stations,prominent_pollutants,aqi_value,air_quality_status,unit
0,30-04-2025,Maharashtra,Amravati,2,PM10,78,Satisfactory,number_of_monitoring_stations in Absolute Numb...
1,30-04-2025,Bihar,Purnia,1,CO,56,Satisfactory,number_of_monitoring_stations in Absolute Numb...
2,30-04-2025,Madhya Pradesh,Katni,1,O3,98,Satisfactory,number_of_monitoring_stations in Absolute Numb...
3,30-04-2025,Chhattisgarh,Tumidih,1,PM10,103,Moderate,number_of_monitoring_stations in Absolute Numb...
4,30-04-2025,Assam,Byrnihat,1,PM2.5,61,Satisfactory,number_of_monitoring_stations in Absolute Numb...
...,...,...,...,...,...,...,...,...
235780,01-04-2022,Bihar,Arrah,1,PM10,210,Poor,number_of_monitoring_stations in Absolute Numb...
235781,01-04-2022,Rajasthan,Jaipur,3,"PM2.5,PM10",158,Moderate,number_of_monitoring_stations in Absolute Numb...
235782,01-04-2022,Maharashtra,Chandrapur,2,PM2.5,201,Poor,number_of_monitoring_stations in Absolute Numb...
235783,01-04-2022,Uttar Pradesh,Varanasi,4,PM10,128,Moderate,number_of_monitoring_stations in Absolute Numb...
235784,01-04-2022,Odisha,Brajrajnagar,1,O3,270,Poor,number_of_monitoring_stations in Absolute Numb...

In [4]:
# Step 1: Clean any invisible whitespace (just to be safe)
aqi1['date'] = aqi1['date'].astype(str).str.strip()

# Step 2: Convert using the exact format
aqi1['date'] = pd.to_datetime(aqi1['date'], format='%d-%m-%Y', errors='coerce')

# Step 4: Verify a few dates
print(aqi1['date'].head())

0   2025-04-30
1   2025-04-30
2   2025-04-30
3   2025-04-30
4   2025-04-30
Name: date, dtype: datetime64[ns]

C:\Users\91935\AppData\Local\Temp\ipykernel_14580\3385762070.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  aqi1['date'] = aqi1['date'].astype(str).str.strip()
C:\Users\91935\AppData\Local\Temp\ipykernel_14580\3385762070.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  aqi1['date'] = pd.to_datetime(aqi1['date'], format='%d-%m-%Y', errors='coerce')

In [5]:
metro_cities = ['Delhi', 'Mumbai', 'Bengaluru', 'Chennai', 'Kolkata', 'Hyderabad']

In [6]:
metrocity=aqi1[aqi1["area"].isin(metro_cities)].copy()
print(metrocity.shape)

(6747, 8)

In [13]:
aqi1['day'] = aqi1['date'].dt.dayofweek
metrocity['date'] = pd.to_datetime(metrocity['date'], errors='coerce')  # convert to datetime if not already
metrocity['day'] = metrocity['date'].dt.dayofweek

In [14]:
metrocity.head(20)

,date,state,area,number_of_monitoring_stations,prominent_pollutants,aqi_value,air_quality_status,unit,day
34,2025-04-30,Tamil Nadu,Chennai,7,"PM10,O3,CO",46,Good,number_of_monitoring_stations in Absolute Numb...,2
92,2025-04-30,West Bengal,Kolkata,6,"PM10,NO2",65,Satisfactory,number_of_monitoring_stations in Absolute Numb...,2
95,2025-04-30,Telangana,Hyderabad,11,"PM2.5,PM10",74,Satisfactory,number_of_monitoring_stations in Absolute Numb...,2
99,2025-04-30,Karnataka,Bengaluru,13,"PM2.5,PM10",84,Satisfactory,number_of_monitoring_stations in Absolute Numb...,2
148,2025-04-30,Maharashtra,Mumbai,15,PM10,61,Satisfactory,number_of_monitoring_stations in Absolute Numb...,2
210,2025-04-30,Delhi,Delhi,36,O3,198,Moderate,number_of_monitoring_stations in Absolute Numb...,2
245,2025-04-29,Karnataka,Bengaluru,12,"PM2.5,PM10",79,Satisfactory,number_of_monitoring_stations in Absolute Numb...,1
339,2025-04-29,Tamil Nadu,Chennai,7,"PM10,CO",42,Good,number_of_monitoring_stations in Absolute Numb...,1
348,2025-04-29,West Bengal,Kolkata,6,"PM2.5,O3",78,Satisfactory,number_of_monitoring_stations in Absolute Numb...,1
355,2025-04-29,Delhi,Delhi,36,PM10,209,Poor,number_of_monitoring_stations in Absolute Numb...,1
441,2025-04-29,Maharashtra,Mumbai,19,PM10,75,Satisfactory,number_of_monitoring_stations in Absolute Numb...,1
448,2025-04-29,Telangana,Hyderabad,14,PM10,71,Satisfactory,number_of_monitoring_stations in Absolute Numb...,1
461,2025-04-28,Delhi,Delhi,33,PM10,266,Poor,number_of_monitoring_stations in Absolute Numb...,0
502,2025-04-28,Telangana,Hyderabad,11,PM10,66,Satisfactory,number_of_monitoring_stations in Absolute Numb...,0
522,2025-04-28,Karnataka,Bengaluru,11,"PM2.5,PM10",76,Satisfactory,number_of_monitoring_stations in Absolute Numb...,0
559,2025-04-28,Tamil Nadu,Chennai,7,"PM10,O3,CO",35,Good,number_of_monitoring_stations in Absolute Numb...,0
606,2025-04-28,West Bengal,Kolkata,7,"PM2.5,PM10",69,Satisfactory,number_of_monitoring_stations in Absolute Numb...,0
610,2025-04-28,Maharashtra,Mumbai,20,PM10,86,Satisfactory,number_of_monitoring_stations in Absolute Numb...,0
667,2025-04-27,West Bengal,Kolkata,7,"PM10,O3",59,Satisfactory,number_of_monitoring_stations in Absolute Numb...,6
713,2025-04-27,Karnataka,Bengaluru,12,"PM2.5,O3",85,Satisfactory,number_of_monitoring_stations in Absolute Numb...,6

In [9]:
aqi_compress=(metrocity.groupby(['area','date_type'])['aqi_value'].mean().reset_index().rename(columns={'area': 'City', 'aqi_value': 'Average AQI'}))

KeyError: 'date_type'

In [10]:
aqi_compress

NameError: name 'aqi_compress' is not defined

In [ ]:
plt.figure(figsize=(10, 6))
sns.barplot(
    data=aqi_compress,
    x='City',
    y='Average AQI',
    hue='date_type',
    palette='Set2'
)

plt.title("Weekend vs Weekday AQI in Indian Metro Cities")
plt.ylabel("Average AQI")
plt.xlabel("Metro City")
plt.legend(title="Day Type")
plt.tight_layout()
plt.show()

In [ ]:
aqi_compress.to_csv('week_and_week_days.csv', index=False)